### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by rmohan19883** [x4nth055/emotion-recognition-using-speech#1]
I ran the pip install requirements.txt and it finished successfully. However when I try to run "python test.py" it gives a invalid syntax issue ->

Rakeshs-MacBook-Air:emotion-recognition-using-speech-master rakeshmohan$ python test.py
  File "test.py", line 180
    print(f"\t{emotion.capitalize()}: {proba*100:.2f}%")
                                                      ^
SyntaxError: invalid syntax
Rakeshs-MacBook-Air:emotion-recognition-using-speech-master rakeshmohan$ 

Can you please help? I am very new to Python and ML etc.

**Comment by x4nth055** [comment]
Hi, I should mention that this repository supports Python 3.6 and above, please consider updating your python version first.

**Comment by rmohan19883** [comment]
I have Python 3.7

**Comment by x4nth055** [comment]
Oh. I have made a couple of changes to test.py  . Please try pulling/cloning again.

**Comment by rmohan19883** [comment]
Thank you !
I downloaded the whole package and tried to run test.py but got a new issue at line 129 this time(the earlier issue was at line 180)

Rakeshs-MacBook-Air:emotion-recognition-using-speech-master-2 rakeshmohan$ python test.py
  File "test.py", line 129
    result = [ f'"{estimator.__class__.__name__}"' for estimator, _, _ in estimators ]
                                                 ^
SyntaxError: invalid syntax
Rakeshs-MacBook-Air:emotion-recognition-using-speech-master-2 rakeshmohan$ pwd
/Users/rakeshmohan/Downloads/emotion-recognition-using-speech-master-2

I am sorry to bother you with all this, if you could , please have a look. Have a great day ahead !!

**Comment by x4nth055** [comment]
I'm pretty sure that f-string formatting is Python 3.6+, try checking your python version by
`import sys
print(sys.version)`
I have removed f-string formatting from test.py.

**Comment by rmohan19883** [comment]
Thanks! however my python version has always been 3.7 so not sure why I was getting f-string errors..

The latest test.py is working now , though with some warning messages with sklearn module, like ->

Python 3.7.3 (default, Jun 19 2019, 07:38:49) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable. Visit
http://www.python.org/download/mac/tcltk/ for current information.
>>> 
 RESTART: /Users/rakeshmohan/Downloads/emotion-recognition-using-speech-master-2/test.py 

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator SVC from version 0.20.2 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.20.2 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Warning (from warnings module):
  File "/usr/local/lib/python3.7/site-packages/sklearn/base.py", line 306
    UserWarning)
UserWarning: Trying to unpickle estimator AdaBoostClassifier from version 0.20.2 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.

Also, the script is not stopping.. this may sound very stupid (apologies for that ) but in order to stop I just need to close the execution window? I thought it will record my voice for a few seconds and then display the sentiments before closing ...

Also not sure if the prediction is accurate .. I tried saying " I am not happy with all this and so I want to close my account , please can you call your manager" .. it gave output as 'neutral' and then like I said above, it went on with displaying neutral ,happy ,etc . I guess it was recording the noise after I stopped talking  and trying to predict it... 

+] Model trained
Test accuracy score: 90.181%
Please talk
neutral
neutral
happy
happy
happy
happy
happy
happy
neutral

Nothing urgent, whenever you have a min - can you please guide me?
After this , I have one favor to ask , but will eagerly wait for your reply :)
Thanks a lot again !!!
Good Night !!

**Comment by x4nth055** [comment]
Hello buddy, I think this is not the place to discuss this, please consider emailing me... xD
`test.py` script was designed just to test the project and the models, the model used in `test.py` isn't even optimal, try testing Example 1 that is mentioned in `README.md`.
- Note that this project is recognizing emotions using the speech tone ( not from speech to text and then analyzing the text ), so try being sad or happy ( or even change the set of emotions ) in your tone. please check the data used and you'll understand ( in `data` folder ).
- Also note that if `test.py` is bothering you, and you want to test emotion just once, then you need to delete the `while loop` in line 170.

**Comment by rmohan19883** [comment]
Thanks again !!
Is there a way to integrate text analysis as well ? or do you think that is not a good idea?
As per your knowledge, can we add GUI around this ? which can show what person is speaking in text format and also display some graphs to show the emotions. I know I am asking a lot but its not intended to trouble you , just trying to understand the possibilities.
