### ISSUE TITLE
Using a pre trained model

### ISSUE THREAD

**Issue by Rhythym** [x4nth055/emotion-recognition-using-speech#10]
Hello, 
I want to use a pre trained model to detect boredom in speech? How can I do that? Can you please share your pre trained model for it?

**Comment by x4nth055** [comment]
Hey there,

Sorry for the late response, it is straightforward:
```python
from emotion_recognition import EmotionRecognizer
# None means do not use any model yet
rec = EmotionRecognizer(None, emotions=["boredom", "neutral"], features=["mfcc"])
# evaluate all models in `grid` folder and determine the best one in terms of test accuracy
rec.determine_best_model()
# now you can make inference on the model
rec.predict("data/emodb/wav/15b09La.wav") # 'boredom'
rec.predict_proba("data/emodb/wav/15b09La.wav") # {'boredom': 0.9428571428571428, 'neutral': 0.05714285714285714}
```

So we're making classification on neutral & boredom speech, it's pretty accurate! Please confirm if this solves your issue.

Thanks,
Rockikz.

**Comment by paddy-03** [comment]
Is it possible to tune the RNN based model for a different combination of labels than the default 5?

**Comment by mshivasharan** [comment]
Hello, Thanks for the code! I tried the above code but, I am getting below error. Could you please help me with this.

ModuleNotFoundError: No module named 'emotion_recognition'

**Comment by zzirend** [comment]
Hello,
Hope you are doing very well.
I run the model in order to determine the best model (with GridSearch). But it runs with the following problem:
'GradientBoostingClassifier' object has no attribute 'presort'


I couldn't fix it. please help me.
Thank you

**Comment by x4nth055** [comment]
Hello @mshivasharan ,

Sorry for taking too long to respond.

You need to be in the same directory as the `emotion_recognition.py` file and run the code.
