### ISSUE TITLE
Issue using predict_proba(emotion_recognizer)

### ISSUE THREAD

**Issue by Argg13** [x4nth055/emotion-recognition-using-speech#11]
When using predict_proba (emotion_recognizer), I get different results based on the order of the chosen emotions.
i.e. if I write "sad","neutral","happy" and then "happy","neutral","sad", my results are different.

**Comment by x4nth055** [comment]
Hey there,

Sorry for the late response, I have updated the code to fix this issue, I was using `emotions` list instead of the `model.classes_` that is provided by Scikit-learn.

Thanks for pointing out!

Rockikz.
