### ISSUE TITLE
Error about rec.determine_best_model(train=True)

### ISSUE THREAD

**Issue by xjtu-wjx** [x4nth055/emotion-recognition-using-speech#12]
When I run this sentence rec.determine_best_model(train=True), the code gives error:ModuleNotFoundError: No module named 'sklearn.ensemble._gb_losses'. How to slove it?Is it about the scikit-learn's version?

**Comment by x4nth055** [comment]
Hey there!

Yes I think this is a version error, I've updated the grid folder to contain models with the updated sklearn's version, also you should upgrade to the latest sklearn version:
```bash
$ pip3 install --upgrade sklearn
```

**Comment by xjtu-wjx** [comment]
Dear sir,i tried a lot and i found this code can only run in the sklearn's version of 0.20.2 or 0.21.2(one of those，I forgot the exact number) in my computer, and too high or too low version of sklearn doesn't work.Thank for your solution and reply.

**Comment by xjtu-wjx** [comment]
Good wishes.Hope you a nice day!

**Comment by x4nth055** [comment]
Yes, this was due the pickled models in `grid` folder were in the past sklearn version, I have updated them for the latest version.

Thanks!
