### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by topchy** [x4nth055/emotion-recognition-using-speech#14]
Hi,

I am very new to working with Python, so this Issue might not be specific to the package, but I could not find anything online, so decided to ask. When I try to install import DeepEmotionRecognizer, I get the following error:

> `---------------------------------------------------------------------------
> 
> TypeError                                 Traceback (most recent call last)
> <ipython-input-230-b7123d9d4e42> in <module>
> ----> 1 from deep_emotion_recognition import DeepEmotionRecognizer
>       2 
> 
> ~/Documents/UCONN/GE/Data/Adam/emotion-recognition-using-speech/deep_emotion_recognition.py in <module>
>      16 from data_extractor import load_data
>      17 from create_csv import write_custom_csv, write_emodb_csv, write_tess_ravdess_csv
> ---> 18 from emotion_recognition import EmotionRecognizer
>      19 from utils import get_first_letters, AVAILABLE_EMOTIONS, extract_feature, get_dropout_str
>      20 
> 
> ~/Documents/UCONN/GE/Data/Adam/emotion-recognition-using-speech/emotion_recognition.py in <module>
>       7 from sklearn.model_selection import GridSearchCV
>       8 
> ----> 9 import matplotlib.pyplot as pl
>      10 from time import time
>      11 from utils import get_best_estimators, get_audio_config
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py in <module>
>      36 import matplotlib.colorbar
>      37 import matplotlib.image
> ---> 38 from matplotlib import rcsetup, style
>      39 from matplotlib import _pylab_helpers, interactive
>      40 from matplotlib import cbook
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/style/__init__.py in <module>
> ----> 1 from .core import use, context, available, library, reload_library
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/style/core.py in <module>
>     222 # Load style library
>     223 # ==================
> --> 224 _base_library = load_base_library()
>     225 
>     226 library = None
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/style/core.py in load_base_library()
>     164 def load_base_library():
>     165     """Load style library defined in this package."""
> --> 166     library = read_style_directory(BASE_LIBRARY_PATH)
>     167     return library
>     168 
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/style/core.py in read_style_directory(style_dir)
>     200         with warnings.catch_warnings(record=True) as warns:
>     201             styles[path.stem] = rc_params_from_file(
> --> 202                 path, use_default_template=False)
>     203         for w in warns:
>     204             _log.warning('In %s: %s', path, w.message)
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
>     983         'c':   'color',
>     984         'fc':  'facecolor',
> --> 985         'ec':  'edgecolor',
>     986         'mew': 'markeredgewidth',
>     987         'aa':  'antialiased',
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in _rc_params_in_file(fname, fail_on_error)
>     914     rcParamsOrig = RcParams(rcParams.copy())
>     915     # This also checks that all rcParams are indeed listed in the template.
> --> 916     # Assiging to rcsetup.defaultParams is left only for backcompat.
>     917     defaultParams = rcsetup.defaultParams = {
>     918         # We want to resolve deprecated rcParams, but not backend...
> 
> ~/anaconda3/lib/python3.7/contextlib.py in __enter__(self)
>     110         del self.args, self.kwds, self.func
>     111         try:
> --> 112             return next(self.gen)
>     113         except StopIteration:
>     114             raise RuntimeError("generator didn't yield") from None
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in _open_file_or_url(fname)
>     891 You have the following UNSUPPORTED LaTeX preamble customizations:
>     892 %s
> --> 893 Please do not ask for support with these customizations active.
>     894 *****************************************************************
>     895 """, '\n'.join(config['text.latex.preamble']))
> 
> ~/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in is_url(filename)
>     886             config['datapath'] = get_data_path(_from_rc=config['datapath'])
>     887 
> --> 888     if "".join(config['text.latex.preamble']):
>     889         _log.info("""
>     890 *****************************************************************
> 
> TypeError: expected string or bytes-like object`

Do you have any idea what is the problem?
I appreciate any insight:)

**Comment by abdoulsn** [comment]
Hello could you show the code you use to import it pleas?

**Comment by topchy** [comment]
Hi, 
I think it worked after all. The problem was in how my Python was installed. Thank you for your willingness to help!
