### ISSUE TITLE
Different Results in Example 1 

### ISSUE THREAD

**Issue by eduardblumental** [x4nth055/emotion-recognition-using-speech#15]
Hi,

I wanted to replicate Example 1 from the README. I didn’t make any changes to the code, but got the output much different from yours: 
 
![image](https://user-images.githubusercontent.com/57115587/96880767-3e665880-1486-11eb-857d-acdcbc79efc9.png)

Also, the best model selection seems rather strange as I used SVC in the first place. I would appreciate it if you could comment on this issue.

Kind Regards,
Eduards

**Comment by x4nth055** [comment]
Hey @eduardblumental ,

Sorry for not getting to you back sooner,

I've added/deleted some samples from `data` folder and didn't update the README results, I'm also getting 69% accuracy on test set with regular `SVC()` model.

After I ran `rec.determine_best_model()`, the resulting model is a tweaked `SVC()` with `C=10` and `gamma=0.001`, and got 88.4% accuracy with it!

Please let me know if you have any questions.
Thanks,
Rockikz
