### ISSUE TITLE
Speech to text problem

### ISSUE THREAD

**Issue by OkicB** [x4nth055/emotion-recognition-using-speech#17]
Hi,
Based on this, I tried to convert speech to text, but whatever I do in the test file is the same print every time, even if I delete from the test file "print ('please talk')", so nothing changes it prints me "please talk" in output. I run the program in order but the output is the same. Also I try to delete some code to make mistake, I thought it wll be an error, but the output is the same.
[+] Model trained
Test accuracy score: 48.677%
Please talk
calm

Thank You in advance.

Best regards.
Bekir

**Comment by x4nth055** [comment]
Hey @OkicB ,

The `test.py` is for testing your own voice by expressing an emotion in your speech. It doesn't convert speech to text.

When the `"please talk"` is printed on your console, then you should start expressing an emotion using the microphone, it'll automatically stop recording when you stop speaking.

Hope this removes the ambiguity,
Thanks,
