### ISSUE TITLE
Error while running the pretrained model: No such file or directory: 'train_custom.csv'

### ISSUE THREAD

**Issue by mshivasharan** [x4nth055/emotion-recognition-using-speech#19]
Hello, Could you please help me in this?

      3 rec = EmotionRecognizer(None, emotions=["boredom", "neutral"], features=["mfcc"])
      4 # evaluate all models in `grid` folder and determine the best one in terms of test accuracy
----> 5 rec.determine_best_model()
      6 # now you can make inference on the model
      7 rec.predict("data/emodb/wav/15b09La.wav") # 'boredom'

10 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   2008         kwds["usecols"] = self.usecols
   2009 
-> 2010         self._reader = parsers.TextReader(src, **kwds)
   2011         self.unnamed_cols = self._reader.unnamed_cols
   2012 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] No such file or directory: 'train_custom.csv'

**Comment by mshivasharan** [comment]
Actually, solved it! Thank you for the great code

**Comment by x4nth055** [comment]
Right, your welcome :)

**Comment by Phoenix0005** [comment]
> Actually, solved it! Thank you for the great code

I have the same issue. Couldn't find the train_custom.csv file. Can you please help me solve this issue?

**Comment by mateosere** [comment]
Can someone post how was it solved? :) Thanks!
