### ISSUE TITLE
Test without training again

### ISSUE THREAD

**Issue by Summarraja** [x4nth055/emotion-recognition-using-speech#21]
How can I just run the model and test emotions of audio file without training the model again?

**Comment by x4nth055** [comment]
Hi @Summarraja ,

Will add that feature very soon, thanks for pointing out!

**Comment by heshamyasser99** [comment]
Is this feature added yet?

**Comment by rekkitcwts** [comment]
Apologies for bumping, but I do have the same question as @Summarraja
