### ISSUE TITLE
Different Results in Example 2

### ISSUE THREAD

**Issue by shushutang2008** [x4nth055/emotion-recognition-using-speech#24]
Hello,

I just ran the Example 2 from the README. I didn’t make any changes to the code, but the confusion_matrix showed that the percentage of ‘happy’ and ‘sad’ were mistaken.

![image](https://user-images.githubusercontent.com/65482662/115981978-3d93b800-a5ca-11eb-8c3d-6248a5a55cac.png)

I would appreciate it if you could comment on this issue.

**Comment by x4nth055** [comment]
Hello @shushutang2008 ,

Sorry for being too late to respond.

You can remove the pre-trained models in the `results` folder so you can re-train with the new data. I'm assuming something went wrong when I cleaned some noisy data samples in the `data` folder.

Hope this helps.
