### ISSUE TITLE
Rnn in deep learning usage is problematic in terms of feature space

### ISSUE THREAD

**Issue by eshalev4** [x4nth055/emotion-recognition-using-speech#25]
Looking at [this blog](https://machinelearningmastery.com/start-here/#deep_learning_time_series), [this tutorial](https://www.simplilearn.com/tutorials/deep-learning-tutorial/rnn), [the Wikipedia entery](https://en.wikipedia.org/wiki/Recurrent_neural_network), and any other material, shows us that RNNs are experts at extracting the time-sequential information in our data. 

The features you extract are averaged across the time domain. Wouldn't it be better to feed the network with temporal information when using LSTM or GRUs?

**Comment by x4nth055** [comment]
Hello @eshalev4 ,

You're absolutely right, the `extract_feature()` function from `utils.py` uses `np.mean()` for taking the average, pull requests are welcomed if you want to contribute!
