### ISSUE TITLE
requesting for configuring process documentation or instruction.

### ISSUE THREAD

**Issue by Oblivion97** [x4nth055/emotion-recognition-using-speech#4]
How can I configure it for my native language?& if I want to test yours, how would I start the training & test the model?

**Comment by x4nth055** [comment]
Hi,
You can use custom data only as mentioned in `README.md`, after deleting my own custom data in `data/train-custom` and `data/test-custom` folders, you can add your own there.
After that, you need to disable default datasets, here is the code for that:
```
from emotion_recognition import EmotionRecognizer
rec = EmotionRecognizer(None, emotions=["sad", "neutral", "happy"], tess_ravdess=False, emodb=False, custom_db=True)
rec.get_samples_by_class()
```
**Outputs: (in my case)**
```
         train  test  total
sad         21    16     37
neutral     21    16     37
happy       21    16     37
total       63    48    111
```
You can find the best model suited automatically:
```
rec.determine_best_model()
```
**Outputs:**
```
[+] Best model determined: MLPClassifier with 77.083% test accuracy
```
To add your custom data, all you need to do is converting your audio samples to 16000 sample rate as mentioned in `README.md` (please read it) and then labeling each sample by its emotion at the end of its name, here is an example: `20190615_014359_sad.wav` will automatically classified as sad sample.

**Comment by Tanish18** [comment]
Hi, 
Can I use your model to detect any other emotion like rudeness using my own custom-dataset? If yes, please guide.

**Comment by kjamesng** [comment]
Hi,
I need to compile the code into an executable file that can't detect emotions in real-time. Can you please guide me through the steps involved. I'm new to this.

**Comment by x4nth055** [comment]
Hey @Tanish18 

Sorry for the late reply, I have fixed the issue, it was caused because the custom dataset doesn't have the emotions you specify.

For instance, if you specify 'angry' emotion, and you do not have angry samples in the custom dataset, it will raise this error, it was there because `balance` is set to True by default. Now I fixed it and it set it to False when there is no samples on some emotion classes.

Thanks.

**Comment by umamaie** [comment]
hiii.. 
actually i want to use it for my final year project can i use this ..? can u please help me to do this work

**Comment by x4nth055** [comment]
Hello @umamaie ,

Yes, you can use it in your project! You can refer to the README file for setting up and getting it to work.

Best,

**Comment by umamaie** [comment]
Ok thankyou

**Comment by umamaie** [comment]
Can you please tell me I want to use in my project EEG signals actually my
project title is "Emotion analysis From EEG signals using Machine learning"
