### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by x4nth055** [x4nth055/emotion-recognition-using-speech#8]
Hi, 
Can I use your model to detect any other emotion like rudeness using my own custom-dataset? If yes, please guide.

_Originally posted by @Tanish18 in https://github.com/x4nth055/emotion-recognition-using-speech/issues/4#issuecomment-617765335_

**Comment by x4nth055** [comment]
Hello,

Yes, you can add your emotion label to `AVAILABLE_EMOTIONS` in `utils.py`.
After that, you should use `convert_wavs.py` to convert your audio samples to usable format.
Finally, you should add your samples to `data` folder under `train-custom` and `test-custom` subfolders and use them as in the README.

Good luck!

**Comment by Tanish18** [comment]
Thank you!
