### ISSUE TITLE
How did you acquire additional actor dataset?

### ISSUE THREAD

**Issue by jangho2001us** [x4nth055/emotion-recognition-using-speech#9]
Hi,

RAVDESS data consists of 24 actors as far as i know.
In your code, you utilize additional actors... 
How did you get these dataset...?

Best,
Jangho

**Comment by x4nth055** [comment]
Hey Jangho, sorry for the late reply, I've actually combined RAVDESS with TESS dataset (the last 2 actors), so the models won't overfit on a particular dataset.
Thanks,
Rockikz
